# Configuracion general del Patio Inteligente

WIFI_SSID = "CAMBIA_AQUI_TU_WIFI"
WIFI_PASSWORD = "CAMBIA_AQUI_TU_CLAVE"

USAR_AP_SI_FALLA = True
AP_SSID = "PatioInteligente"
AP_PASSWORD = "patio1234"

HTTP_PORT = 80
WIFI_TIMEOUT_S = 15

DURACION_RIEGO_MS = 5000
INTERVALO_FIESTA_MS = 500

BOMBA_ACTIVA_EN_ALTO = True
RGB_ANODO_COMUN = False

TAMANO_MAX_SOLICITUD = 4096
TAMANO_CHUNK = 1024

# Archivos del frontend
FRONTEND_DIR = "frontend"

# Pines
PIN_SERVO_PUERTA = 13
PIN_SERVO_SILLA = 14
PIN_BOMBA_FUENTE = 25
PIN_BOMBA_RIEGO = 26
PIN_RGB_R = 18
PIN_RGB_G = 19
PIN_RGB_B = 21

# Posiciones de servos
PUERTA_CERRADA = 0
PUERTA_ABIERTA = 90
SILLA_IZQUIERDA = 30
SILLA_CENTRO = 90
SILLA_DERECHA = 150

# PWM
SERVO_FREQ = 50
SERVO_MIN_US = 500
SERVO_MAX_US = 2400
RGB_FREQ = 1000
